/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

/**
 *
 * @author mptri
 */
public class TaskDialogScreen extends javax.swing.JDialog {

    /**
     * Creates new form ProjectDialogScreen
     */
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectDialogTitlePanel = new javax.swing.JPanel();
        ProjectDIalogTitle = new javax.swing.JLabel();
        ProjectDialogIcon = new javax.swing.JLabel();
        ProjectDialogRegister = new javax.swing.JPanel();
        RegisterName = new javax.swing.JLabel();
        RegisterNameTextBox = new javax.swing.JTextField();
        RegisterDescription = new javax.swing.JLabel();
        RegisterDescriptionTextbox = new javax.swing.JTextField();
        RegisterDeadline = new javax.swing.JLabel();
        RegisterDeadlineText = new javax.swing.JTextField();
        RegisterNotes = new javax.swing.JLabel();
        RegisterNotesText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ProjectDialogTitlePanel.setBackground(new java.awt.Color(255, 51, 51));

        ProjectDIalogTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProjectDIalogTitle.setForeground(new java.awt.Color(255, 255, 255));
        ProjectDIalogTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProjectDIalogTitle.setText("Tarefas");

        ProjectDialogIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProjectDialogIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N

        javax.swing.GroupLayout ProjectDialogTitlePanelLayout = new javax.swing.GroupLayout(ProjectDialogTitlePanel);
        ProjectDialogTitlePanel.setLayout(ProjectDialogTitlePanelLayout);
        ProjectDialogTitlePanelLayout.setHorizontalGroup(
            ProjectDialogTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectDialogTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectDIalogTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProjectDialogIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ProjectDialogTitlePanelLayout.setVerticalGroup(
            ProjectDialogTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectDialogTitlePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ProjectDialogTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectDialogIcon)
                    .addComponent(ProjectDIalogTitle))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        RegisterName.setText("Nome");

        RegisterDescription.setText("Descrição");

        RegisterDeadline.setText("Prazo");

        RegisterDeadlineText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterDeadlineTextActionPerformed(evt);
            }
        });

        RegisterNotes.setText("Notas");

        javax.swing.GroupLayout ProjectDialogRegisterLayout = new javax.swing.GroupLayout(ProjectDialogRegister);
        ProjectDialogRegister.setLayout(ProjectDialogRegisterLayout);
        ProjectDialogRegisterLayout.setHorizontalGroup(
            ProjectDialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectDialogRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProjectDialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ProjectDialogRegisterLayout.createSequentialGroup()
                        .addGroup(ProjectDialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterNotesText)
                            .addComponent(RegisterDeadlineText)
                            .addComponent(RegisterDescriptionTextbox)
                            .addGroup(ProjectDialogRegisterLayout.createSequentialGroup()
                                .addComponent(RegisterDescription)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(RegisterNameTextBox)
                            .addComponent(RegisterName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegisterDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        ProjectDialogRegisterLayout.setVerticalGroup(
            ProjectDialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectDialogRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterName)
                .addGap(8, 8, 8)
                .addComponent(RegisterNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegisterDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterDescriptionTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterDeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(RegisterDeadlineText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegisterNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterNotesText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProjectDialogTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectDialogRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProjectDialogTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProjectDialogRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterDeadlineTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterDeadlineTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterDeadlineTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProjectDIalogTitle;
    private javax.swing.JLabel ProjectDialogIcon;
    private javax.swing.JPanel ProjectDialogRegister;
    private javax.swing.JPanel ProjectDialogTitlePanel;
    private javax.swing.JLabel RegisterDeadline;
    private javax.swing.JTextField RegisterDeadlineText;
    private javax.swing.JLabel RegisterDescription;
    private javax.swing.JTextField RegisterDescriptionTextbox;
    private javax.swing.JLabel RegisterName;
    private javax.swing.JTextField RegisterNameTextBox;
    private javax.swing.JLabel RegisterNotes;
    private javax.swing.JTextField RegisterNotesText;
    // End of variables declaration//GEN-END:variables
}
