	/* Explorando o procedure*/
-- Procedures são como funções, mas tem uma vantagem de poder iniciar transações, dar commit e rollback

-- Criando uma tabela e introduzindo valores
create table accounts (
    id int generated by default as identity,
    name varchar(100) not null,
    balance dec(15,2) not null,
    primary key(id)
);

insert into accounts(name,balance) values('Bob',10000) returning id; 	-- Aqui adicionamos o retuning, quando o insert for executado 
insert into accounts(name,balance) values('Alice',10000) returning id;	-- ele retornará o id criado

-- Criaremos uma procedure que fará transferencia entre duas contas
create or replace procedure transfer(sender_id integer, reciever_id integer, amount integer) as $$
	begin
		-- Removendo valor da conta de quem envia
		update accounts
		set balance = balance - amount
		where id = sender_id;
		-- Adicionando valor a conta de quem receberá
		update accounts
		set balance = balance + amount
		where id = reciever_id;
	commit;
end; $$ language plpgsql
		
-- Para executar a procedure usamos o call
call transfer (1,2,1000);
		
select * from accounts;		
		
		
		
		
		
		
		
		
		
		
		