/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TaskApp;
//package Controller;

import java.sql.Connection;
import util.ConnectionFactory;

public class App {
    public static void main(String[] args) {
        //conectando a database
        Connection c = ConnectionFactory.getConnection();
        
        ////Testando salvar o projeto////////////
        Controller.ProjectController projectController = new Controller.ProjectController();
        
        Model.Project project = new Model.Project();
        project.setName("Primeiro Projeto");
        project.setDescription("Projeto teste");
        projectController.save(project);

        //fechando a conexão coma database
        ConnectionFactory.closeConnection(c);
    }
}
